services:
  postgres:
    image: registry.docker.ir/postgres:17.5
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=scary_story_generator
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  minio:
    image: registry.docker.ir/minio/minio:latest
    ports:
      - "9000:9000" # api
      - "9001:9001" # ui
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  redis:
    image: registry.docker.ir/redis:8.0.1
    ports:
      - 6379:6379
    volumes:
      - redis_data:/var/lib/redis/data

volumes:
  postgres_data:
  minio_data:
  redis_data:
