import type { Metadata } from "next"
import { Creepster, Geist } from "next/font/google"
import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
})

const creepster = Creepster({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-creepster"
})

export const metadata: Metadata = {
  title: "Scary story generator",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${creepster.variable} ${geistSans.variable} font-sans antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
